version: "3"
services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
      - https_proxy=fra1.sme.zscalertwo.net:9480
      - http_proxy=fra1.sme.zscalertwo.net:9480
  chrome:
    image: selenium/node-chrome
    depends_on:
      - selenium-hub
    ports:
      - "5900:5900"
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
      - https_proxy=fra1.sme.zscalertwo.net:9480
      - http_proxy=fra1.sme.zscalertwo.net:9480
  firefox:
    image: selenium/node-firefox
    depends_on:
      - selenium-hub
    ports:
      - "5901:5901"
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
      - https_proxy=fra1.sme.zscalertwo.net:9480
      - http_proxy=fra1.sme.zscalertwo.net:9480
